---
- name: Verify the carlos user was created
  hosts: servidores
  become: true
  gather_facts: false

  tasks:

    - name: Check if carlos user exists
      ansible.builtin.getent:
        database: passwd
        key: carlos
      register: carlos_info
      failed_when: carlos_info.failed
      changed_when: false

    - name: Carlos was created
      ansible.builtin.debug:
        msg: "Carlos was created"
      when: carlos_info is defined and not carlos_info.failed

    - name: Output carlos user status to file
      ansible.builtin.lineinfile:
        path: /home/student/verify.txt
        line: "Carlos was created"
        create: true
      when: carlos_info is defined and not carlos_info.failed
